version: '3.7'

volumes:
    node-modules:

services:
  frontend:
    container_name: rlhfblender-ui
    image: rlhfblender-ui:latest
    build:
      context: ./rlhfblender-ui/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    volumes:
      - ./rlhfblender-ui/:/usr/src/app/
      - node-modules:/usr/src/app/node_modules/

  backend:
    container_name: rlhfblender-backend
    image: rlhfblender-backend:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PARENT_IMAGE=mambaorg/micromamba:1.5-jammy
        - PYTORCH_DEPS=cpuonly
    ports:
      - "8080:8080"
    command: ["python", "rlhfblender/app.py", "--port", "8080", "--db-host", "sqlite:///data/rlhfblender.db"]
    volumes:
      - ./remote_data/:/home/mambauser/rlhfblender/data/
      - ./rlhfblender_model/:/home/mambauser/rlhfblender/rlhfblender_model/:ro
      - ./logs/:/home/mambauser/rlhfblender/logs/
      - ./multi-type-feedback/feedback/:/home/mambauser/rlhfblender/multi-type-feedback/feedback/
      - ./multi-type-feedback/gt_agents/:/home/mambauser/rlhfblender/multi-type-feedback/gt_agents/:ro
      - ./multi-type-feedback/reward_models/:/home/mambauser/rlhfblender/multi-type-feedback/reward_models/
      - ./multi-type-feedback/samples/:/home/mambauser/rlhfblender/multi-type-feedback/samples/
      - ./multi-type-feedback/train_baselines/gt_agents/:/home/mambauser/rlhfblender/multi-type-feedback/train_baselines/gt_agents/:ro
      - ./multi-type-feedback/train_baselines/dynamic_rlhf_agents/:/home/mambauser/rlhfblender/multi-type-feedback/train_baselines/dynamic_rlhf_agents/
